spring:
  application:
    name: Spring-REST
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    password: "postgres"
    username: "postgres"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
app:
  version: 1.0.0
