spring:
  application:
    name: Spring-REST
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    password: "postgres"
    username: "postgres"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
    open-in-view: false

  security:
    user:
      name: sahil
      password: 12345

app:
  version: 1.0.0
